apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecomops
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shahryar371/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_USER_API
              value: http://localhost:3001
            - name: VITE_PRODUCT_API
              value: http://localhost:3002
            - name: VITE_CART_API
              value: http://localhost:3003
            - name: VITE_ORDER_API
              value: http://localhost:3004
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ecomops
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
  type: ClusterIP
