apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecomops

resources:
  - namespace.yml
  - secret.yml
  - configmap.yml
  - postgres.yml
  - user-service.yml
  - deployment.yml
  - cart-service.yml
  - payment-service.yml
  - order-service.yml
  - frontend.yml

images:
  - name: shahryar371/user-service
    newTag: latest
  - name: shahryar371/product-service
    newTag: latest
  - name: shahryar371/cart-service
    newTag: latest
  - name: shahryar371/order-service
    newTag: latest
  - name: shahryar371/payment-service
    newTag: latest
  - name: shahryar371/frontend
    newTag: latest
