apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ecomops
data:
  01-create-databases.sql: |
    CREATE DATABASE shopsphere_users;
    CREATE DATABASE shopsphere_products;
    CREATE DATABASE shopsphere_cart;
    CREATE DATABASE shopsphere_orders;
    CREATE DATABASE shopsphere_payments;
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecomops
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ecomops
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: shopsphere-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopsphere-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "shopsphere"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "shopsphere"]
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 2Gi
            
